# Generated by Django 4.2.7 on 2024-03-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.CharField(blank=True, max_length=100, null=True)),
                ('Destination', models.CharField(blank=True, max_length=100, null=True)),
                ('Person', models.CharField(blank=True, max_length=100, null=True)),
                ('Kids', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
