# Generated by Django 4.2.7 on 2024-03-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0003_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thailand', models.CharField(blank=True, max_length=100, null=True)),
                ('California', models.CharField(blank=True, max_length=100, null=True)),
                ('Japan', models.CharField(blank=True, max_length=100, null=True)),
                ('Turkey', models.CharField(blank=True, max_length=100, null=True)),
                ('Venice', models.CharField(blank=True, max_length=100, null=True)),
                ('Chinna', models.CharField(blank=True, max_length=100, null=True)),
                ('Singapor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
